#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
split_by_path_plan.py - T2.5path1: 按语义切割方案重切 segment 图片

根据 path_cut_plan_*.json 中的 bbox 信息，将原图切割成多个 segment，
并生成 manifest JSON、Markdown 和 contact/debug 图。

Usage:
    python split_by_path_plan.py --plan path_cut_plan.json --image source.jpg
    python split_by_path_plan.py --plan path_cut_plan.json --image source.jpg --output-dir ./output
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


def load_cut_plan(plan_path: str) -> dict:
    """加载切割方案 JSON"""
    with open(plan_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def crop_segment(image: Image.Image, bbox: list) -> Image.Image:
    """根据 bbox [x1, y1, x2, y2] 裁剪图片"""
    x1, y1, x2, y2 = bbox
    return image.crop((x1, y1, x2, y2))


def create_output_dir(base_dir: str, timestamp: str, fixed_name: bool = False) -> str:
    """创建输出目录"""
    if fixed_name:
        output_dir = os.path.join(base_dir, "segments")
    else:
        output_dir = os.path.join(base_dir, f"path_segments_{timestamp}")
    os.makedirs(output_dir, exist_ok=True)
    return output_dir


def generate_segment_image(image: Image.Image, segment: dict, output_dir: str) -> str:
    """生成单个 segment 图片，返回保存路径"""
    segment_id = segment['segment_id']
    bbox = segment['crop_bbox']
    
    # 裁剪
    cropped = crop_segment(image, bbox)
    
    # 保存
    filename = f"segment_{segment_id:02d}.png"
    filepath = os.path.join(output_dir, filename)
    cropped.save(filepath, 'PNG')
    
    return filepath


def generate_manifest_json(
    image_path: str,
    source_cut_plan: str,
    segments: list,
    output_dir: str,
    timestamp: str,
    fixed_name: bool = False,
) -> str:
    """生成 manifest JSON 文件"""
    manifest = {
        "image_path": image_path,
        "source_cut_plan": source_cut_plan,
        "segment_count": len(segments),
        "timestamp": timestamp,
        "segments": []
    }

    for seg in segments:
        segment_entry = {
            "segment_id": seg['segment_id'],
            "proposed_name": seg['proposed_name'],
            "image_path": f"segment_{seg['segment_id']:02d}.png",
            "crop_bbox": seg['crop_bbox'],
            "expected_topics": seg.get('expected_topics', []),
            "expected_path_examples": seg.get('expected_path_examples', []),
            "notes": seg.get('notes', '')
        }
        manifest['segments'].append(segment_entry)

    # 保存 JSON
    manifest_filename = "manifest.json" if fixed_name else f"path_segments_manifest_{timestamp}.json"
    manifest_path = os.path.join(output_dir, manifest_filename)
    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    
    return manifest_path


def generate_manifest_md(
    image_path: str,
    source_cut_plan: str,
    segments: list,
    output_dir: str,
    timestamp: str,
    fixed_name: bool = False,
) -> str:
    """生成 manifest Markdown 文件"""
    md_content = f"""# Path Segments Manifest

**生成时间**: {timestamp}
**原图**: `{image_path}`
**来源切割方案**: `{source_cut_plan}`

---

## 概览

- **Segment 总数**: {len(segments)}
- **切割策略**: 语义块切割 (semantic_block_based)

---

## Segment 详情

"""
    
    for seg in segments:
        bbox = seg['crop_bbox']
        height = bbox[3] - bbox[1]
        
        md_content += f"""### Segment {seg['segment_id']:02d}: {seg['proposed_name']}

| 属性 | 值 |
|------|-----|
| **文件名** | segment_{seg['segment_id']:02d}.png |
| **裁剪区域** | y: {bbox[1]} - {bbox[3]} px |
| **高度** | {height} px |

**预期覆盖题材**:
"""
        for topic in seg.get('expected_topics', []):
            md_content += f"- {topic}\n"
        
        md_content += "\n**预期路径示例**:\n"
        for path_example in seg.get('expected_path_examples', []):
            md_content += f"- `{path_example}`\n"
        
        md_content += f"\n**备注**: {seg.get('notes', '无')}\n\n---\n\n"
    
    # 下一步说明
    md_content += """## 下一步: T2.5path2

本 manifest 供 T2.5path2 消费，用于：

1. 对每个 segment 进行多模态内容识别
2. 提取实际的题材路径和股票列表
3. 将识别结果与 `expected_path_examples` 对比验证
4. 输出标准化的 path 结构数据

### 消费方式

```python
# 读取 manifest
with open('path_segments_manifest_*.json', 'r') as f:
    manifest = json.load(f)

# 遍历每个 segment
for seg in manifest['segments']:
    image_path = seg['image_path']  # 相对路径
    expected_paths = seg['expected_path_examples']  # 预期路径
    # 进行多模态识别...
```

---

*Generated by split_by_path_plan.py | Task T2.5path1*
"""
    
    # 保存 Markdown
    md_filename = "manifest.md" if fixed_name else f"path_segments_manifest_{timestamp}.md"
    md_path = os.path.join(output_dir, md_filename)
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(md_content)
    
    return md_path


def generate_contact_image(
    image: Image.Image,
    segments: list,
    output_dir: str,
    timestamp: str,
    fixed_name: bool = False,
) -> str:
    """生成 contact/debug 图，显示所有 segment 的边界"""
    # 创建副本用于标注
    debug_img = image.copy()
    draw = ImageDraw.Draw(debug_img)
    
    # 尝试加载字体
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 24)
        small_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 16)
    except:
        font = ImageFont.load_default()
        small_font = ImageFont.load_default()
    
    # 颜色列表
    colors = [
        '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7',
        '#DDA0DD', '#98D8C8', '#F7DC6F', '#BB8FCE'
    ]
    
    # 绘制每个 segment 的边界
    for i, seg in enumerate(segments):
        bbox = seg['crop_bbox']
        color = colors[i % len(colors)]
        
        # 绘制矩形边框
        draw.rectangle(
            [(bbox[0], bbox[1]), (bbox[2], bbox[3])],
            outline=color,
            width=4
        )
        
        # 绘制标签背景
        label = f"#{seg['segment_id']:02d} {seg['proposed_name'][:15]}"
        text_bbox = draw.textbbox((0, 0), label, font=font)
        text_width = text_bbox[2] - text_bbox[0]
        text_height = text_bbox[3] - text_bbox[1]
        
        label_y = bbox[1] + 10
        draw.rectangle(
            [(bbox[0] + 5, label_y), (bbox[0] + 15 + text_width, label_y + text_height + 10)],
            fill=color
        )
        
        # 绘制文字
        draw.text(
            (bbox[0] + 10, label_y + 2),
            label,
            fill='white',
            font=font
        )
        
        # 绘制高度标注
        height_text = f"{bbox[3] - bbox[1]}px"
        draw.text(
            (bbox[0] + 10, bbox[3] - 25),
            height_text,
            fill=color,
            font=small_font
        )
    
    # 保存 contact 图
    contact_filename = "manifest_contact.png" if fixed_name else f"path_segments_manifest_{timestamp}_contact.png"
    contact_path = os.path.join(output_dir, contact_filename)
    debug_img.save(contact_path, 'PNG')
    
    return contact_path


def parse_args():
    """解析命令行参数"""
    parser = argparse.ArgumentParser(
        description='按语义切割方案重切 segment 图片 (T2.5path1)',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python split_by_path_plan.py --plan output/path_cut_plan_20260409_221150.json --image source.jpg
  python split_by_path_plan.py --plan plan.json --image img.jpg --output-dir ./output
        """
    )
    parser.add_argument(
        '--plan',
        type=str,
        required=True,
        help='切割方案 JSON 文件路径 (必需)'
    )
    parser.add_argument(
        '--image',
        type=str,
        required=True,
        help='原图文件路径 (必需)'
    )
    parser.add_argument(
        '--output-dir',
        type=str,
        default='output',
        help='输出目录 (默认: output)'
    )
    parser.add_argument(
        '--fixed-name',
        action='store_true',
        help='使用固定文件名（无时间戳），由 orchestrator 控制输出目录'
    )
    return parser.parse_args()


def main():
    """主函数"""
    args = parse_args()
    
    # 从参数获取路径
    plan_path = args.plan
    image_path = args.image
    output_base_dir = args.output_dir
    
    # 生成时间戳
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    print(f"[T2.5path1] 开始按语义方案切割图片...")
    print(f"  切割方案: {plan_path}")
    print(f"  原图: {image_path}")
    
    # 加载切割方案
    plan = load_cut_plan(plan_path)
    segments = plan['segments']
    
    print(f"  计划生成 {len(segments)} 个 segments")
    
    # 打开原图
    print(f"  加载原图...")
    image = Image.open(image_path)
    print(f"  原图尺寸: {image.size}")
    
    # 创建输出目录
    output_dir = create_output_dir(output_base_dir, timestamp, fixed_name=args.fixed_name)
    print(f"  输出目录: {output_dir}")

    # 生成每个 segment 图片
    print(f"  生成 segment 图片...")
    for seg in segments:
        filepath = generate_segment_image(image, seg, output_dir)
        height = seg['crop_bbox'][3] - seg['crop_bbox'][1]
        print(f"    ✓ Segment {seg['segment_id']:02d}: {os.path.basename(filepath)} "
              f"(y:{seg['crop_bbox'][1]}-{seg['crop_bbox'][3]}, h:{height}px)")

    # 生成 manifest JSON
    print(f"  生成 manifest JSON...")
    source_cut_plan = os.path.basename(plan_path)
    manifest_json_path = generate_manifest_json(
        image_path, source_cut_plan, segments, output_dir, timestamp,
        fixed_name=args.fixed_name,
    )
    print(f"    ✓ {os.path.basename(manifest_json_path)}")

    # 生成 manifest Markdown
    print(f"  生成 manifest Markdown...")
    manifest_md_path = generate_manifest_md(
        image_path, source_cut_plan, segments, output_dir, timestamp,
        fixed_name=args.fixed_name,
    )
    print(f"    ✓ {os.path.basename(manifest_md_path)}")

    # 生成 contact/debug 图
    print(f"  生成 contact/debug 图...")
    contact_path = generate_contact_image(
        image, segments, output_dir, timestamp,
        fixed_name=args.fixed_name,
    )
    print(f"    ✓ {os.path.basename(contact_path)}")
    
    print(f"\n[T2.5path1] 完成!")
    print(f"  输出目录: {output_dir}")
    print(f"  Segment 数量: {len(segments)}")
    print(f"\n下一步: T2.5path2 将对每个 segment 进行多模态内容识别")


if __name__ == "__main__":
    main()